from collections import defaultdict
from itertools import pairwise

import pytest

from solution.task_3 import generate, learn

EPSILON = 0.05
weights = {
    "$": {
        "a": 1,
        "elephants": 8,
        "snakes": 11,
        "tigers": 3,
        "dolphins": 1,
        "nights": 1,
        "seagulls": 4,
        "hippos": 1,
        "squirrels": 4,
        "some": 1,
        "ostriches": 1,
        "spiders": 6,
        "robins": 1,
        "iguanas": 1,
        "tornadoes": 1,
        "deer": 3,
        "rats": 3,
        "seals": 7,
        "hawks": 1,
        "kangaroos": 1,
        "sparrows": 8,
        "newts": 6,
        "swans": 2,
        "dogs": 4,
        "sheep": 2,
        "wolves": 1,
        "lions": 2,
        "yaks": 6,
        "walruses": 1,
        "hedgehogs": 1,
        "rabbits": 2,
    },
    "a": {"rabbit": 1, "slow": 1},
    "rabbit": {"ran": 1},
    "ran": {"into": 1},
    "into": {"the": 3, "hidden": 1, "their": 2},
    "the": {
        "apple": 1,
        "rocks": 1,
        "wild": 1,
        "open": 2,
        "desert": 1,
        "sandy": 1,
        "shallow": 2,
        "autumn": 1,
        "dark": 1,
        "blue": 1,
        "warm": 1,
        "fields": 1,
        "early": 2,
        "narrow": 1,
        "rocky": 1,
        "towering": 1,
        "grassy": 1,
        "quiet": 1,
        "fallen": 2,
        "lake": 1,
        "cool": 3,
        "trees": 2,
        "meadow": 1,
        "bright": 1,
        "damp": 1,
        "high": 1,
        "icy": 1,
        "ocean": 2,
        "ball": 1,
        "tall": 2,
        "day": 1,
        "mountain": 1,
        "sea": 2,
        "branches": 1,
        "harsh": 1,
        "large": 1,
        "woods": 1,
        "thin": 1,
        "sun-warmed": 1,
        "rough": 1,
        "waves": 1,
        "shore": 1,
        "wooden": 2,
        "grass": 1,
        "break": 1,
        "snow": 1,
        "shade": 1,
        "hills": 1,
        "dusty": 1,
        "water": 1,
        "frozen": 1,
        "mossy": 1,
        "thick": 2,
        "harbor": 1,
        "breeze": 1,
        "hard": 1,
        "air": 1,
    },
    "apple": {"orchard": 1},
    "orchard": {"^": 1},
    "elephants": {
        "enjoy": 1,
        "trumpet": 2,
        "bathe": 1,
        "walk": 1,
        "rest": 1,
        "drink": 1,
        "trample": 1,
    },
    "enjoy": {"eating": 1},
    "eating": {"large": 1},
    "large": {"apples": 1, "trees": 1},
    "apples": {"^": 1},
    "snakes": {
        "slither": 1,
        "can": 1,
        "hiss": 1,
        "shed": 1,
        "hide": 1,
        "coil": 1,
        "hunt": 1,
        "dart": 1,
        "strike": 1,
        "lie": 1,
        "weave": 1,
        "flick": 1,
    },
    "slither": {"around": 1},
    "around": {"the": 1},
    "rocks": {"at": 1, "during": 1, "^": 2},
    "at": {"night": 2, "passing": 1, "the": 2, "dusk": 2},
    "night": {"^": 2},
    "tigers": {"are": 1, "pounce": 1, "chase": 1},
    "are": {"great": 1, "cold": 1, "excited": 1, "scared": 1, "happy": 1},
    "great": {"hunters": 1, "destruction": 1},
    "hunters": {"in": 1},
    "in": {"the": 21, "a": 1, "their": 2, "circles": 1},
    "wild": {"^": 1},
    "dolphins": {"swim": 1},
    "swim": {"across": 1, "close": 1, "slowly": 1, "quickly": 1},
    "across": {"the": 7},
    "open": {"ocean": 1, "plains": 1},
    "ocean": {"^": 2, "for": 1},
    "nights": {"are": 1},
    "cold": {"in": 1, "^": 1},
    "desert": {"wilderness": 1},
    "wilderness": {"^": 1},
    "seagulls": {"glide": 1, "dive": 1, "soar": 1, "screech": 1},
    "glide": {"over": 1, "gracefully": 1, "effortlessly": 1},
    "over": {"the": 2},
    "sandy": {"beach": 1},
    "beach": {"^": 1},
    "hippos": {"sleep": 1},
    "sleep": {"in": 1},
    "shallow": {"river": 1, "water": 1},
    "river": {"waters": 1, "^": 1},
    "waters": {"^": 1},
    "squirrels": {"gather": 1, "leap": 1, "chase": 1, "nibble": 1},
    "gather": {"nuts": 1, "in": 1},
    "nuts": {"in": 1},
    "autumn": {"forest": 1},
    "forest": {"^": 1},
    "some": {"snakes": 1},
    "can": {"climb": 1, "cause": 1},
    "climb": {"up": 1},
    "up": {"tall": 1, "the": 1, "when": 1, "to": 1, "and": 1},
    "tall": {"trees": 1, "grass": 1, "reeds": 1},
    "trees": {"^": 5},
    "ostriches": {"run": 1},
    "run": {"fast": 1, "quickly": 1},
    "fast": {"on": 1},
    "on": {"the": 9, "their": 1},
    "plains": {"^": 2},
    "spiders": {"spin": 2, "crawl": 2, "catch": 1, "weave": 1},
    "spin": {"webs": 1, "their": 1},
    "webs": {"in": 2, "^": 1, "at": 1},
    "dark": {"corners": 1},
    "corners": {"^": 1},
    "robins": {"fly": 1},
    "fly": {"high": 1, "overhead": 1},
    "high": {"across": 1, "mountains": 1, "above": 1},
    "blue": {"sky": 1},
    "sky": {"^": 1},
    "iguanas": {"bask": 1},
    "bask": {"in": 1},
    "warm": {"sunlight": 1, "at": 1},
    "sunlight": {"^": 1},
    "tornadoes": {"can": 1},
    "cause": {"great": 1},
    "destruction": {"^": 1},
    "trumpet": {"when": 1, "loudly": 1},
    "when": {"they": 4},
    "they": {"are": 3, "grow": 1, "fly": 1, "dive": 1, "feel": 1},
    "excited": {"^": 1},
    "deer": {"roam": 1, "move": 1, "jump": 1},
    "roam": {"the": 1},
    "fields": {"in": 1},
    "early": {"morning": 1, "evening": 1},
    "morning": {"^": 1},
    "rats": {"scurry": 2, "gnaw": 1},
    "scurry": {"through": 1, "along": 1},
    "through": {"the": 7},
    "narrow": {"streets": 1},
    "streets": {"^": 1},
    "hiss": {"to": 1},
    "to": {
        "warn": 1,
        "the": 1,
        "branch": 1,
        "mark": 1,
        "catch": 1,
        "keep": 1,
        "smell": 1,
        "their": 1,
    },
    "warn": {"their": 1},
    "their": {
        "predators": 1,
        "territory": 1,
        "skin": 1,
        "prey": 2,
        "unsuspecting": 1,
        "webs": 1,
        "tails": 2,
        "feathers": 1,
        "surroundings": 1,
        "frightened": 1,
        "delicate": 1,
        "burrows": 1,
        "nests": 1,
        "tongues": 1,
        "hidden": 1,
    },
    "predators": {"^": 1},
    "seals": {"swim": 2, "rest": 1, "playfully": 1, "bark": 1, "bob": 1, "glide": 1},
    "close": {"to": 1},
    "rocky": {"shores": 1},
    "shores": {"^": 2},
    "hawks": {"hunt": 1},
    "hunt": {"from": 1, "small": 1},
    "from": {"the": 2, "branch": 1},
    "towering": {"trees": 1},
    "leap": {"from": 1},
    "branch": {"to": 1, "^": 1},
    "kangaroos": {"hop": 1},
    "hop": {"across": 1, "along": 1, "into": 1},
    "grassy": {"plains": 1},
    "sparrows": {
        "chirp": 1,
        "flutter": 2,
        "perch": 1,
        "sing": 1,
        "hop": 1,
        "gather": 1,
        "rest": 1,
    },
    "chirp": {"in": 1},
    "quiet": {"dawn": 1},
    "dawn": {"^": 2},
    "newts": {"hide": 1, "crawl": 2, "live": 1, "swim": 1, "blend": 1},
    "hide": {"under": 2},
    "under": {"the": 2, "rocks": 1},
    "fallen": {"leaves": 1, "tree": 1},
    "leaves": {"^": 1},
    "swans": {"glide": 1, "preen": 1},
    "gracefully": {"across": 1},
    "lake": {"^": 1},
    "bathe": {"in": 1},
    "cool": {"mud": 1, "wet": 1, "river": 1},
    "mud": {"^": 1},
    "dogs": {"bark": 1, "run": 1, "chase": 1, "wag": 1},
    "bark": {"loudly": 1, "as": 1},
    "loudly": {"at": 2},
    "passing": {"strangers": 1},
    "strangers": {"^": 1},
    "chase": {"each": 1, "their": 1, "after": 1},
    "each": {"other": 1},
    "other": {"up": 1},
    "sheep": {"graze": 1, "rest": 1},
    "graze": {"peacefully": 1, "on": 1},
    "peacefully": {"in": 1},
    "meadow": {"^": 1},
    "wolves": {"howl": 1},
    "howl": {"at": 1},
    "bright": {"full": 1},
    "full": {"moon": 1},
    "moon": {"^": 1},
    "crawl": {"slowly": 1, "into": 1, "across": 2},
    "slowly": {"in": 2},
    "damp": {"soil": 1},
    "soil": {"^": 1},
    "lions": {"roar": 1, "stalk": 1},
    "roar": {"to": 1},
    "mark": {"their": 1},
    "territory": {"^": 1},
    "yaks": {"wander": 1, "graze": 1, "survive": 1, "huddle": 1, "trek": 1, "chew": 1},
    "wander": {"through": 1},
    "mountains": {"^": 1},
    "shed": {"their": 1},
    "skin": {"as": 1},
    "as": {"they": 3},
    "grow": {"^": 1},
    "walruses": {"rest": 1},
    "rest": {"on": 2, "under": 1, "in": 1, "quietly": 1},
    "icy": {"shores": 1},
    "dive": {"into": 2},
    "for": {"fish": 1, "food": 1, "their": 1, "safety": 1},
    "fish": {"^": 1},
    "hedgehogs": {"curl": 1},
    "curl": {"up": 1},
    "scared": {"^": 1},
    "quickly": {"to": 1, "through": 1, "past": 1},
    "catch": {"the": 1, "insects": 1},
    "ball": {"^": 1},
    "stalk": {"their": 1},
    "prey": {"through": 1, "^": 3},
    "grass": {"^": 3},
    "during": {"the": 1},
    "day": {"^": 1},
    "mountain": {"slopes": 1},
    "slopes": {"^": 1},
    "soar": {"high": 1},
    "above": {"the": 1},
    "sea": {"^": 2},
    "walk": {"in": 1},
    "slow": {"procession": 1},
    "procession": {"^": 1},
    "live": {"in": 1},
    "wet": {"ponds": 1},
    "ponds": {"^": 1},
    "flutter": {"between": 1, "gently": 1},
    "between": {"the": 2},
    "branches": {"^": 2},
    "hidden": {"spaces": 1, "homes": 1},
    "spaces": {"^": 1},
    "coil": {"up": 1},
    "keep": {"warm": 1},
    "pounce": {"on": 1},
    "unsuspecting": {"prey": 1},
    "survive": {"in": 1},
    "harsh": {"winter": 1},
    "winter": {"cold": 1},
    "insects": {"in": 1},
    "screech": {"as": 1},
    "overhead": {"^": 1},
    "move": {"silently": 1},
    "silently": {"through": 1},
    "woods": {"^": 1},
    "perch": {"on": 1},
    "thin": {"branches": 1},
    "small": {"animals": 1},
    "animals": {"for": 1},
    "food": {"^": 1},
    "tails": {"in": 1, "when": 1},
    "circles": {"^": 1},
    "sun-warmed": {"rocks": 1},
    "rough": {"ground": 1},
    "ground": {"^": 1},
    "water": {"^": 2},
    "playfully": {"splash": 1},
    "splash": {"in": 1},
    "waves": {"^": 1},
    "preen": {"their": 1},
    "feathers": {"on": 1},
    "shore": {"^": 1},
    "along": {"the": 2},
    "wooden": {"beams": 1, "posts": 1},
    "beams": {"^": 1},
    "dart": {"quickly": 1, "back": 1},
    "sing": {"at": 1},
    "break": {"of": 1},
    "of": {"dawn": 1, "the": 1},
    "blend": {"into": 1},
    "surroundings": {"^": 1},
    "huddle": {"together": 1},
    "together": {"in": 1},
    "snow": {"^": 1},
    "weave": {"intricate": 1, "between": 1},
    "intricate": {"webs": 1},
    "shade": {"of": 1},
    "hills": {"^": 1},
    "strike": {"when": 1},
    "feel": {"threatened": 1},
    "threatened": {"^": 1},
    "gnaw": {"on": 1},
    "posts": {"nearby": 1},
    "nearby": {"^": 1},
    "bob": {"up": 1},
    "and": {"down": 1},
    "down": {"in": 1},
    "wag": {"their": 1},
    "happy": {"^": 1},
    "dusty": {"path": 1},
    "path": {"^": 1},
    "effortlessly": {"through": 1},
    "after": {"their": 1},
    "frightened": {"prey": 1},
    "trek": {"across": 1},
    "frozen": {"tundra": 1},
    "tundra": {"^": 1},
    "evening": {"light": 1},
    "light": {"^": 1},
    "mossy": {"rocks": 1},
    "delicate": {"webs": 1},
    "dusk": {"^": 2},
    "lie": {"still": 1},
    "still": {"waiting": 1},
    "waiting": {"for": 1},
    "rabbits": {"hop": 1, "dart": 1},
    "burrows": {"for": 1},
    "safety": {"^": 1},
    "chew": {"on": 1},
    "thick": {"green": 1, "jungle": 1},
    "green": {"grass": 1},
    "quietly": {"in": 1},
    "nests": {"^": 1},
    "reeds": {"^": 1},
    "past": {"the": 1},
    "harbor": {"boats": 1},
    "boats": {"^": 1},
    "drink": {"from": 1},
    "gently": {"in": 1},
    "breeze": {"^": 1},
    "nibble": {"on": 1},
    "hard": {"acorns": 1},
    "acorns": {"^": 1},
    "flick": {"their": 1},
    "tongues": {"to": 1},
    "smell": {"the": 1},
    "air": {"^": 1},
    "trample": {"through": 1},
    "jungle": {"^": 1},
    "jump": {"over": 1},
    "tree": {"trunks": 1},
    "trunks": {"^": 1},
    "back": {"to": 1},
    "homes": {"^": 1},
}


@pytest.mark.parametrize(
    "input_dataset_path,expected_weights",
    [("tests/llm_dataset.txt", weights)],
)
def test_llm(input_dataset_path, expected_weights):
    with open(input_dataset_path) as f:
        weights: defaultdict[str, defaultdict[str, int | float]] = defaultdict(
            lambda: defaultdict(lambda: 0)
        )

        state = learn(f.readlines())
        for _ in range(100_000):
            s = ("$ " + generate(state) + " ^").split()
            for last, curr in pairwise(s):
                weights[last][curr] += 1

        assert set(weights.keys()) == set(expected_weights.keys())

        for word, a in weights.items():
            b = expected_weights[word]
            assert len(a) == len(b)

            s_a = sum(a.values())
            for k in a:
                a[k] /= s_a

            s_b = sum(b.values())
            for k in b:
                b[k] /= s_b
                assert abs(a[k] - b[k]) < EPSILON
